/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package base;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JFrame;

/**
 *
 * @author ASUS
 */
public class Daftar extends javax.swing.JFrame {

    static String getid_pengguna() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * Creates new form Daftar
     */
    public Daftar() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
        id_pengguna();
    }
    

    public void id_pengguna() {
        try {
            String sql = "SELECT id_pengguna FROM pengguna order by id_pengguna desc";
            Connection conn = (Connection) CONNECTION.Conec.GetConnection();
            Statement stm = conn.createStatement();
            ResultSet rs = stm.executeQuery(sql);

            if (rs.next()) {
                String idK = rs.getString("id_pengguna").substring(2);
                String AN = "" + (Integer.parseInt(idK) + 1);
                String Nol = "";
                if (AN.length() == 1) {
                    Nol = "0";
//                } else if (AN.length() == 2) {
//                    Nol = "0";
                } else if (AN.length() == 3) {
                    Nol = "";

                }

                this.idPengguna.setText("US" + Nol + AN);
            } else {
                this.idPengguna.setText("US01");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR " + e.getMessage());
        } 
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nama = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        namapanggilan = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        NoTelp = new javax.swing.JTextField();
        idPengguna = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nama.setBackground(new java.awt.Color(0,0,0,1)
        );
        nama.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        nama.setBorder(null);
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 560, 30));

        alamat.setBackground(new java.awt.Color(0,0,0,1)
        );
        alamat.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        alamat.setBorder(null);
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 560, 30));

        namapanggilan.setBackground(new java.awt.Color(0,0,0,1)
        );
        namapanggilan.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        namapanggilan.setBorder(null);
        getContentPane().add(namapanggilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, 570, 40));

        simpan.setBackground(new java.awt.Color(0,0,0,1)
        );
        simpan.setBorder(null);
        simpan.setContentAreaFilled(false);
        simpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 650, 120, 40));

        pass.setBackground(new java.awt.Color(0,0,0,1)
        );
        pass.setBorder(null);
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 590, 560, 40));

        NoTelp.setBackground(new java.awt.Color(0,0,0,1)
        );
        NoTelp.setBorder(null);
        getContentPane().add(NoTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 560, 40));

        idPengguna.setBackground(new java.awt.Color(0,0,0,1));
        getContentPane().add(idPengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 236, 550, 30));

        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(893, 10, 90, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TAMPILAN/RegistrasiNew.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1280, 800));
        jLabel1.setMinimumSize(new java.awt.Dimension(1280, 800));
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 800));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 770));

        setSize(new java.awt.Dimension(1007, 803));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        String id_pengguna = this.idPengguna.getText(),
        nama_pengguna = this.nama.getText(),
        no_telp = this.NoTelp.getText(),
        alamat = this.alamat.getText(),
        username = this.namapanggilan.getText();
        String password = this.pass.getText();
        try {
            
            String sql = "INSERT INTO `pengguna`(`id_pengguna`, `nama_pengguna`, `no_telp`, `alamat`, `username`, `password`) VALUES ('"+id_pengguna+"','"+nama_pengguna+"','"+no_telp+"','"+alamat+"','"+username+"',password('"+password+"'))";
            Connection conn = (Connection) CONNECTION.Conec.GetConnection();
            PreparedStatement pst = conn.prepareStatement(sql);
//            pst.setString(1, id_pengguna);
//            pst.setString(2, nama_pengguna);
//            pst.setString(3, no_telp);
//            pst.setString(4, alamat);
//            pst.setString(5, username);
//            pst.setString(6, password);
            pst.executeUpdate();
            
            
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
            new Login().setVisible(true);
            this.dispose();
            conn.close();
      
            
        
        }catch(SQLException ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error : " + ex.getMessage());
        }
        id_pengguna();
    }//GEN-LAST:event_simpanActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Daftar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NoTelp;
    private javax.swing.JTextField alamat;
    private javax.swing.JLabel idPengguna;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField namapanggilan;
    private javax.swing.JPasswordField pass;
    private javax.swing.JButton simpan;
    // End of variables declaration//GEN-END:variables
}
